import { useEffect, useMemo, useState } from 'react'
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import AsyncStorage from '@react-native-async-storage/async-storage'

type Task={id:string;title:string;category:string;urgency:number;impact:number;alignment:number;effortHours:number;completedAt?:string}
const key='apcc.mobile.workspace.v1'; const seed:Task[]=[{id:'1',title:'Finish project proposal',category:'Education',urgency:5,impact:5,alignment:5,effortHours:2},{id:'2',title:'Tailor resume',category:'Career',urgency:4,impact:5,alignment:5,effortHours:1.5},{id:'3',title:'Schedule grocery pickup',category:'Family',urgency:4,impact:3,alignment:4,effortHours:.25}]
const score=(task:Task)=>Math.round((task.urgency*8+task.impact*7+task.alignment*4+Math.max(0,6-task.effortHours)*2.5)*10)/10
export default function Today(){const [tasks,setTasks]=useState<Task[]>(seed);const [title,setTitle]=useState('');const [ready,setReady]=useState(false);useEffect(()=>{AsyncStorage.getItem(key).then(raw=>{if(raw)setTasks(JSON.parse(raw));setReady(true)}).catch(()=>setReady(true))},[]);useEffect(()=>{if(ready)AsyncStorage.setItem(key,JSON.stringify(tasks))},[tasks,ready]);const ranked=useMemo(()=>[...tasks].filter(task=>!task.completedAt).sort((a,b)=>score(b)-score(a)),[tasks]);const add=()=>{const value=title.trim();if(!value)return;setTasks(items=>[...items,{id:String(Date.now()),title:value,category:'Inbox',urgency:3,impact:3,alignment:3,effortHours:1}]);setTitle('')};return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>LOCAL WORKSPACE</Text><Text style={s.title}>Today</Text><Text style={s.copy}>{ready?'Saved on this device.':'Loading local workspace...'}</Text><View style={s.card}><Text style={s.heading}>Quick capture</Text><View style={s.row}><TextInput value={title} onChangeText={setTitle} placeholder="Add a task..." placeholderTextColor="#8ea2bd" style={s.input}/><Pressable onPress={add} style={s.add}><Text style={s.addText}>Add</Text></Pressable></View></View><View style={s.card}><Text style={s.heading}>Top priorities</Text>{ranked.map((task,index)=><View key={task.id} style={s.task}><View style={s.rank}><Text style={s.rankText}>{index+1}</Text></View><View style={s.taskBody}><Text style={s.taskTitle}>{task.title}</Text><Text style={s.meta}>{task.category} · Score {score(task)} · {task.effortHours}h</Text></View><Pressable onPress={()=>setTasks(items=>items.map(item=>item.id===task.id?{...item,completedAt:new Date().toISOString()}:item))}><Text style={s.done}>Done</Text></Pressable></View>)}</View><Text style={s.footer}>This starter stores tasks locally. AI connections and cross-device sync remain opt-in future features.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#07111f'},content:{padding:20,gap:16},eyebrow:{color:'#7dd3fc',fontWeight:'800',fontSize:12,letterSpacing:1.3},title:{color:'#eaf1ff',fontSize:42,fontWeight:'800'},copy:{color:'#aabbd1',fontSize:16,lineHeight:23},card:{backgroundColor:'#10223c',borderWidth:1,borderColor:'#25446d',borderRadius:16,padding:16},heading:{color:'#eaf1ff',fontWeight:'800',fontSize:18,marginBottom:12},row:{flexDirection:'row',gap:8},input:{flex:1,backgroundColor:'#07111f',color:'#eaf1ff',borderRadius:10,padding:12,borderWidth:1,borderColor:'#3d5b83'},add:{backgroundColor:'#38bdf8',paddingHorizontal:14,justifyContent:'center',borderRadius:10},addText:{fontWeight:'800',color:'#06111d'},task:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderBottomWidth:1,borderColor:'#25446d'},rank:{width:28,height:28,borderRadius:14,backgroundColor:'#38bdf8',alignItems:'center',justifyContent:'center'},rankText:{fontWeight:'900',color:'#06111d'},taskBody:{flex:1},taskTitle:{color:'#eaf1ff',fontWeight:'700',fontSize:16},meta:{color:'#aabbd1',marginTop:4},done:{color:'#7dd3fc',fontWeight:'800'},footer:{color:'#8ea2bd',lineHeight:20,paddingVertical:8}})
